version: '3'
services:
  express-app:
    image: express-demo
    container_name: express-container
    build: ./ExpressApp 
    ports:
      - "5000:5000"   


  react-app:
    image: reactapp-demo
    container_name: react-container
    build: ./reactapp 
    ports:
      - "3000:3000"



networks:
  custom-app-network:
    external: true
